# Generated by Django 4.2 on 2025-01-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('addressline1', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
                ('creditlimit', models.IntegerField()),
                ('notes', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
